### ISSUE TITLE
Config issues

### ISSUE THREAD

**Issue by jaxxstorm** [litaio/lita-slack#102]
I'm using lita 4.7.0 and lita-slack 1.7.2

My config looks like this:

```
config.adapters.slack.token = "#{ENV['SLACK_TOKEN']}"
config.adapters.slack.link_names = false
```

```
[2016-08-02 04:07:10 UTC] FATAL: Lita configuration file could not be processed. The exception was:
undefined method `link_names=' for #<Lita::Configuration:0x00556d0c3993c8>
Full backtrace:
/srv/lita-docker/lita_config.rb:18:in `block in <top (required)>'
```

What am I getting wrong here?

**Comment by jimmycuadra** [comment]
That configuration attribute is not in version 1.7.2. It's only on the master branch and hasn't been released as a gem yet. The README for 1.7.2 is what you want: https://github.com/litaio/lita-slack/tree/v1.7.2
