### ISSUE TITLE
about two weeks ago, lita bot cannot hear message from itself

### ISSUE THREAD

**Issue by sonnguyen-logigear** [litaio/lita-slack#120]
For example : 
1.Run **@lita-bot function1**
2.lita-bot will reply **function2** (function2 : I had set **command** is **false** to route command)
expected : lita-bot will call **function2**
observed: in message_handler.rb : can not receive message **function2**
Note : It can call **function2** before ( about 1 or 2 week agon)

Any suggestions are highly appreciated!

**Comment by sonnguyen-logigear** [comment]
@jimmycuadra Can you help me about this case?

**Comment by jimmycuadra** [comment]
Lita has never intentionally responded to messages from itself. See https://github.com/litaio/lita/blob/81121a81ead81007c2a808795f9a3bdf535e6a7e/lib/lita/route_validator.rb#L32

**Comment by sonnguyen-logigear** [comment]
I got it, thx you
