### ISSUE TITLE
incoming webhooks not being caught

### ISSUE THREAD

**Issue by metaliu** [litaio/lita-slack#27]
I have messages coming into a channel through an incoming webhook that lita-slack can't intercept.  It would be nice to have an event fire when it notices an incoming webhook.

**Comment by scopp** [comment]
i modified this plugin code locally to allow all messages to be dispatched, even bot messages.  However, it seems webhook messages still cannot be intercepted.  Any thoughts on this would be appreciated!

**Comment by jimmycuadra** [comment]
Is this referring to Lita's HTTP routes, or something in Slack called a webhook?

**Comment by scopp** [comment]
@jimmycuadra https://api.slack.com/incoming-webhooks

**Comment by jimmycuadra** [comment]
Ah, yes. This would be categorized as a bot/integration, and so Lita will not see these as incoming messages. Lita is really designed for doing things in response to explicit commands from humans, generally via chat, but also via its own HTTP server. Sorry!

**Comment by scopp** [comment]
@jimmycuadra yeah, like I said, I modified this on my own fork so bot to bot communication would be possible.  This opens up a lot of possibilities; you should really think about implementing on your end.

**Comment by jaybrueder** [comment]
+1

We also run into situations where it would be good that a webhook can issue commands to the bot

**Comment by rohitagarwal11** [comment]
Hi, 
Any update on this? Can anyone help me how i can make lita to read incoming webhook text to be read as route?

**Comment by jimmycuadra** [comment]
There is no plan to add this functionality at this time, sorry.
