### ISSUE TITLE
Receive post-plugin message content

### ISSUE THREAD

**Issue by gerwitz** [litaio/lita-slack#29]
Using the Giphy integration as an example: when a user uses `/giphy sometag`, Lita receives exactly that. I would like to also know what the outcome of the command was, e.g. the URL that was posted to the channel.

(I'm concerned this is a limitation of the Slack API, but it's worth asking.)

**Comment by jimmycuadra** [comment]
This won't be possible, I'm afraid, because messages from other bots and integrations are intentionally ignored by Lita. It's really designed to do things in response to human commands.
