### ISSUE TITLE
Lita::Room's name is not correct

### ISSUE THREAD

**Issue by brodock** [litaio/lita-slack#44]
When inspecting a room_object from a response in a handler, the name it display's there is a copy of the ID (using lita-slack adapter).

I believe that this adapter is missing a call to https://api.slack.com/methods/channels.info to fill the correct channel name.

**Comment by brodock** [comment]
This is what I receive, instead of the name, it replicates the ID:
#<Lita::Room:0x007f272a53e730 @id="C030B1KQ6", @metadata={}, @name="C030B1KQ6">

You can see this behavior using my plugin: https://github.com/brodock/lita-queue
There is an walkthrough here : https://github.com/brodock/lita-queue/issues/1

**Comment by jimmycuadra** [comment]
`Lita::Adapters::Slack::SlackChannel` is the class where this information is extracted from the raw data sent by Slack. At a glance it looks correct to me, but clearly it's not. I would be happy to accept a PR to fix this!

**Comment by kingcons** [comment]
I'm also experiencing this bug. For whatever reason, a workaround that returns the correct information is doing `Lita::Room.find_by_id("1234abcd").name` or conversely, `Lita::Room.find_by_name("foobarbazquux").id`. If this is still open when I get back from the beach in a week, I'll submit a patch.

**Comment by brodock** [comment]
I still have to do a little debug, but suspect Slack isn't following its own API documentation for RTM's API

**Comment by liamdawson** [comment]
I can confirm @kingcons workaround succeeds, unless it's a private conversation, in which case the room cannot be found.

**Comment by indirect** [comment]
Still seeing this happen today, where `response.message.source.room_object` has a `name` that is actually the Slack room ID, where `Lita::Room.find_by_id(response.message.source.room_object.id)` has a `name` that is the correct name of the channel. :/
