### ISSUE TITLE
Allow to know if a message is coming from a bot

### ISSUE THREAD

**Issue by elia** [litaio/lita-slack#52]
Not sure how this fits within the Lita gem API but something like `response.user.robot?` would be great.

Bot users can be detected by checking that the `subtype=bot_message` as it's done to check [if the message is coming from the current bot](https://github.com/kenjij/lita-slack/blob/f9d08bf19b708c616302384c4bf7e226cdf0b51a/lib/lita/adapters/slack/message_handler.rb#L123)

I'd be happy to submit a PR but not without agreeing on the right API first :white_check_mark:

**Comment by jimmycuadra** [comment]
I suppose it'd be reasonable to add a hash of optional chat-service-specific metadata to `Lita::Message`.

**Comment by jimmycuadra** [comment]
On second thought, this should be done by adding metadata to the `Lita::User` object created for the bot user, since it's a property of the user, not the message, and user objects already support metadata.

**Comment by jimmycuadra** [comment]
Closing because messages from bots should not have been supported in the first place. This was fixed for 1.8.0.
