### ISSUE TITLE
Capability to add a reaction to a message

### ISSUE THREAD

**Issue by liamdawson** [litaio/lita-slack#73]
Slack's API supports adding an emoji response to a message: https://api.slack.com/methods/reactions.add

I'd like this capability so that a user knows that Lita's heard them, and is processing the message, as I have a task that runs 2–5 network calls off the one message, so it can take a while to get a response. (and responding with a ":+1" would send a notification to everyone in the channel).

**Comment by jimmycuadra** [comment]
Something like #61?

**Comment by liamdawson** [comment]
The other end - add the reaction that would cause that event.

**Comment by jimmycuadra** [comment]
Ah, I see. I'll consider this a feature request! If you want to take a shot at implementing it, `Lita::Adapters::Slack::ChatService` is the place it should go.

**Comment by liamdawson** [comment]
I'm looking into it now, the one thing I don't know about at the moment, is that I need to identify the message by an exact timestamp. I'm assuming this is received from Slack, so if you don't currently store it, where can I attach it to the message?

**Comment by liamdawson** [comment]
It's the `ts` property on the incoming data. It isn't currently stored. Is something like `extensions` on the Message object suitable?

**Comment by jimmycuadra** [comment]
Looks like the raw message event data ultimately gets sent to `Lita::Adapters::Slack::MessageHandler`, but the timestamp and other raw data from the event don't get sent on to the robot. Thus far that class has been a private API, but we could think about exposing it somehow.

**Comment by liamdawson** [comment]
How should that be approached?

**Comment by jimmycuadra** [comment]
It does seem like this needs to be stored on the message. There is an `extensions` hash on the response object, but that gets created later in the message dispatch process after the information you want has already been lost. An alternative that wouldn't require changing Lita itself would be firing a custom event that has all the data, but that's awkward because then you'd have two different ways to handle messages with the Slack adapter.

**Comment by jimmycuadra** [comment]
I'm going to close this because we're not going to add more Slack-specific functionality to the adapter in the future. I'd recommend using a dedicated Slack API gem from any handlers where you want this functionality.
