### ISSUE TITLE
lita-slack not capable with Lita master

### ISSUE THREAD

**Issue by kirs** [litaio/lita-slack#83]
At Shopify, we love new features from Lita master and try to stay on the upstream.
But with the last upstream update, we found that `lita-slack` stopped working.

Unfortunately there is no stacktrace in the Lita log. Here is all we've got:

```
2016-03-01_09:33:51.77846 Outbound message failed: NoMethodError: undefined method `im_for' for nil:NilClass
```

@jimmycuadra

**Comment by jimmycuadra** [comment]
Lita's master branch is never considered stable and is not recommended for production usage—only tagged releases are suitable for a real Lita deploy. The master branch is quite in flux right now with a revamp of the routing system for Lita 5, so it's bound to be breaking various plugins out there on a commit-by-commit basis. Rest assured that Lita 5 will be thoroughly tested with all the official adapters and many major open source handlers before it is released. :}
