### ISSUE TITLE
Remove bot_message and me_message from supported_message_subtypes

### ISSUE THREAD

**Issue by tristaneuan** [litaio/lita-slack#94]
Context: In https://github.com/litaio/lita/pull/191 @jimmycuadra suggested modifying lita-slack to ignore bot messages automatically as a simpler alternative to a configurable ignore list. While following up on this suggestion, I discovered here (https://github.com/litaio/lita-slack/blob/b8c527b17bbb76fd4f2d0925c7f75e3e895121ee/lib/lita/adapters/slack/message_handler.rb#L194) that the adapter already checks the message subtype (https://api.slack.com/events/message) and allows `bot_message`s and `me_message`s to be dispatched to the robot.

I can't think of a particular scenario where this behavior is actually desirable:
1. In my experience, a user who wishes to send a message or command to be received by the bot will not attempt to do so with a `/me` message. In fact, a Lita response to a `/me` message is usually unexpected.
2. The reason given for ignoring messages from self (preventing infinite loops, see https://github.com/litaio/lita/blob/c3ae7d0d994fd0f15f5f18290920b49ca7e3441b/lib/lita/route_validator.rb#L55) also applies to messages from bots in general. For example, I added the `ignore` configuration option to lita-jira (https://github.com/esigler/lita-jira/pull/8/commits/7f8fda2d393e4fe462287fa6297d5cd28c8b10a2) precisely because our Lita instance was responding to JIRA issue IDs it detected in messages sent by our JIRA Slack integration, resulting in spammy duplicate output.

For these reasons, I am proposing the removal of `bot_message` and `me_message` from the array of `supported_message_subtypes`. Pending feedback, I can submit a pull request enacting this change.

**Comment by jimmycuadra** [comment]
I'm +1 on removing bot messages and -1 on removing me messages. A message sent by another bot will never be intended to trigger a Lita route. If someone wants to integrate Lita with an external service, it should be done via explicit web hooks, not by passing messages through chat. For me messages, I see this more as a different presentation style for a message sent by a human, and so we shouldn't assume the user's intent. For example, "/me does thing" and "I did thing" are semantically the same. The differene is only in how the person chooses to express themselves. I agree that it's unlikely a me message would be intended to trigger a command route, but there are also the less common message routes that should still pick up matching patterns anywhere in messages (think lita-karma).

**Comment by jimmycuadra** [comment]
Closed by #95.

**Comment by ericboehs** [comment]
Damn. This broke our lita-bot. We have librato report to an #alerts channel. At certain thresholds (e.g. no one is responding), librato issues a HELPPPPP alert in which lita responds by restarting our servers.

**Comment by jimmycuadra** [comment]
Sorry, Eric. I suppose technically this was a breaking change, but I'm didn't think anyone actually had Lita listen to non-human input intentionally. It'd definitely be a more robust approach to use a web hook for the kind of integration you describe.

**Comment by tristaneuan** [comment]
It may be worth making this configurable in order to support different use cases. Thoughts, @jimmycuadra?

**Comment by tristaneuan** [comment]
Scratch that, I posted before seeing the related pull request.

**Comment by AlexanderPavlenko** [comment]
Thanks Slack support for pointing me to this page after I asked them why bot cannot see messages from other bot 😕 
So, those who want this can fork and `git revert a233d14e1932090fde649d0919b547bfc2fd416b`, because it seems not to be configurable.
