### ISSUE TITLE
Feature Request: Interactive Buttons

### ISSUE THREAD

**Issue by ehaselwanter** [litaio/lita-slack#97]
How do you think about supporting https://api.slack.com/docs/message-buttons

**Comment by jimmycuadra** [comment]
Dupe of litaio/lita#192. Also see discussion in #93 for why there won't be any more Slack-specific features supported at the adapter level.

**Comment by ehaselwanter** [comment]
understood. any thoughts about how to share common code, so that plugin authors can opt-in?

**Comment by jimmycuadra** [comment]
I guess it depends on what needs to be shared. In some cases all that's needed is a simple API call to Slack, which only involves a client library. I'm not sure what the use cases are that would require a deeper integration with Lita, but we can address them and find a good approach as they come up. One possible way is a Lita extension plugin. That might not even be necessary, but we'll see.
